#!/usr/bin/env bash
function cleanup_git_branches() {
    main_branch = $1 || "main"
    ignore_regex = $2 || "main"

    git fetch --all

    BRANCHES=`git branch --merged main | grep -vE '$ignore_regex'`

    if [ "$BRANCHES" == "" ]; then
        echo
        echo "*** No local branches to clean ***"
        exit 1
    fi
    echo Deleting branches:
    echo $BRANCHES

    git branch --merged main | grep -vE '$ignore_regex' | xargs git branch -d
}
